bot:
  rabbitmq:
    exchange: direct-exchange
    queue: mq-queue
    routing-key: mq-exchange-routing-key
  telegram:
    api:
      token: <BOT_TOKEN>
      user-name: <BOT_USER_NAME>

spring:
  main:
    allow-bean-definition-overriding: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/kf_telegram_bot
    username: postgres
    password: root
  liquibase:
    change-log: classpath:liquibase/changelog-master.yml